# Generated by Django 2.2.1 on 2019-06-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
